// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"qcc-tmp-deloy-commit/app/dao/internal"
)

// statisticsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type statisticsDao struct {
	*internal.StatisticsDao
}

var (
	// Statistics is globally public accessible object for table statistics operations.
	Statistics = statisticsDao{
		internal.NewStatisticsDao(),
	}
)

// Fill with you ideas below.
