// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// Statistics is the golang structure for table statistics.
type Statistics struct {
	Id       int    `orm:"id,primary" json:"id"`       //
	Project  string `orm:"project"    json:"project"`  //
	Category string `orm:"category"   json:"category"` //
	Describe string `orm:"describe"   json:"describe"` //
	Persion  string `orm:"persion"    json:"persion"`  //
	Taskid   string `orm:"taskid"     json:"taskid"`   //
	Time     string `orm:"time"       json:"time"`     //
}
